### ISSUE TITLE
OpenSSL 1.0.2 update causes unresolved symbols on darwin x86_64

### ISSUE THREAD

**Issue by ijsf** [EricssonResearch/openwebrtc#230]
OpenSSL has been updated from version 1.0.1h to 1.0.2 in commit 3f34e4bb8c50ea4286cc142e202ccd48be9e8d0b.

Unfortunately, 1.0.2 does currently not compile on armv7 (iOS) due to unresolved symbols in the openssl linking step. This is probably a OpenSSL issue, but I have filed it here just for consistency.

To work around this issue, the above commit can be reverted so that 1.0.1h is used for armv7.

Problem also occurs on OS X.

**Comment by sdroege** [comment]
Can you paste the error messages, plus some lines above?

**Comment by ford-prefect** [comment]
I hit what might be this problem on OS X (bunch of undefined symbols in the linking step) -- wiping out the source directory and rebuilding fixed it.

**Comment by ford-prefect** [comment]
I'm seeing this on armv7s - https://gist.githubusercontent.com/ford-prefect/0ede4650aa86e1807363/raw/8bf46b90c08689ce3f09700ec365140813bdcbe0/openssl-compile.log

**Comment by ijsf** [comment]
The error messages are identical to those posted by ford-prefect.

**Comment by ford-prefect** [comment]
I've got a fix for this at https://github.com/nirbheek/cerbero/pull/12 -- not merging it directly because I'd like to make sure the openssl patch looks okay to push upstream as well

**Comment by ijsf** [comment]
Update: problem also occurs on OS X.

**Comment by nirbheek** [comment]
This is fixed in the Cerbero build thanks to @ford-prefect's patch.

**Comment by superdump** [comment]
I'm getting OpenSSL build issues again after updating yesterday. So are others: https://github.com/EricssonResearch/openwebrtc/issues/233#issuecomment-83256448 I checked the config.log and it showed that the check for SSL_library_init failed due to unresolved symbols. Are we really sure it is linking against the correct OpenSSL?

**Comment by ikonst** [comment]
The cause: We're no longer using the pkgconfig patch, and the autoconf just does -lssl (and not -lcrypto). On static builds, -lcrypto is not pulled by dependency, and that's why autoconf fails.

https://github.com/nirbheek/cerbero/commit/5eae63059643751862534a7a1053129245c001e2 should fix this by removing OpenSSL dependency entirely.

**Comment by nirbheek** [comment]
@superdump, could you test this and see if the problem has gone away?

**Comment by superdump** [comment]
I rebuilt on my laptop just now and it seems to be fine. @ijsf do you still see this or is this OK to close?

**Comment by ijsf** [comment]
@superdump, unfortunately this is still happening on my system. Log: https://gist.github.com/ijsf/65fc28c9fc01c9559f3b

Not sure why this is happening.

**Comment by superdump** [comment]
@ijsf do you still see this or can we close it?

**Comment by ijsf** [comment]
Reopened as this is still not fixed on OS X...

**Comment by superdump** [comment]
Does building from scratch work?

**Comment by ijsf** [comment]
Strangely enough the problem seems to have fixed itself after a `./cerbero-uninstalled wipe`. Apparently removal of the `sources` directory is not enough.

**Comment by ijsf** [comment]
Still having issues, I've narrowed it down to the following:

`./cerbero-uninstalled -c config/darwin-x86_64.config buildone openssl` fails at building OpenSSL.

`./cerbero-uninstalled buildone openssl` succeeds at building OpenSSL.
